//women
export const womenColNames = [
  {
    name: "Alpha",
    season: "SS2024",
    coverLink: `/women/alpha/8.jpg`,
    hoverCover: `/women/alpha/2.jpg`,
  },
  {
    name: "Stella",
    season: "SS2024",
    coverLink: `/women/stella/1.jpg`,
    hoverCover: `/women/stella/7-2.jpg`,
  },
];

export const alphaCol = [
  {
    id: 1,
    imgLink: `/women/alpha/1.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 890,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 2,
    imgLink: `/women/alpha/2.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 890,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 3,
    imgLink: `/women/alpha/3.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1100,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 4,
    imgLink: `/women/alpha/4.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1240,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 5,
    imgLink: `/women/alpha/5.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1240,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 6,
    imgLink: `/women/alpha/6.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 990,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 7,
    imgLink: `/women/alpha/7.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1100,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 8,
    imgLink: `/women/alpha/8.jpg`,
    name: "Alpha Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1100,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
];

export const stellaCol = [
  {
    id: 1,
    imgLink: `/women/stella/1.jpg`,
    secondImgLink: `/women/stella/1-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 2,
    imgLink: `/women/stella/2.jpg`,
    secondImgLink: `/women/stella/2-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 3,
    imgLink: `/women/stella/3.jpg`,
    secondImgLink: `/women/stella/3-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 4,
    imgLink: `/women/stella/4.jpg`,
    secondImgLink: `/women/stella/4-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 5,
    imgLink: `/women/stella/5.jpg`,
    secondImgLink: `/women/stella/5-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 6,
    imgLink: `/women/stella/6.jpg`,
    secondImgLink: `/women/stella/6-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 7,
    imgLink: `/women/stella/7.jpg`,
    secondImgLink: `/women/stella/7-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 8,
    imgLink: `/women/stella/8.jpg`,
    secondImgLink: `/women/stella/8-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 9,
    imgLink: `/women/stella/9.jpg`,
    secondImgLink: `/women/stella/9-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 10,
    imgLink: `/women/stella/10.jpg`,
    secondImgLink: `/women/stella/10-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 11,
    imgLink: `/women/stella/11.jpg`,
    secondImgLink: `/women/stella/11-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 12,
    imgLink: `/women/stella/12.jpg`,
    secondImgLink: `/women/stella/12-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 13,
    imgLink: `/women/stella/13.jpg`,
    secondImgLink: `/women/stella/13-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 14,
    imgLink: `/women/stella/14.jpg`,
    secondImgLink: `/women/stella/14-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 15,
    imgLink: `/women/stella/15.jpg`,
    secondImgLink: `/women/stella/15-2.jpg`,
    name: "Stella Dress",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
];

//men

export const stellaManCol = [
  {
    id: 1,
    imgLink: `/men/stella/1.jpg`,
    secondImgLink: `/men/stella/1.jpg`,
    name: "Stella Suit",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 2,
    imgLink: `/men/stella/2.jpg`,
    secondImgLink: `/men/stella/2-2.jpg`,
    name: "Stella Suit",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 3,
    imgLink: `/men/stella/3.jpg`,
    secondImgLink: `/men/stella/3-2.jpg`,
    name: "Stella Suit",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 4,
    imgLink: `/men/stella/4.jpg`,
    secondImgLink: `/men/stella/4-2.jpg`,
    name: "Stella Suit",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 5,
    imgLink: `/men/stella/5.jpg`,
    secondImgLink: `/men/stella/5.jpg`,
    name: "Stella Suit",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
  {
    id: 6,
    imgLink: `/men/stella/6.jpg`,
    secondImgLink: `/men/stella/6.jpg`,
    name: "Stella Suit",
    description:
      "For additional details, simply scan the QR code to directly connect with one of our team members who can assist you with services, product details, and other information needed.",
    price: 1000,
    details: [
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
      "Natural lamb skin",
      "Regular Fit",
      "No pockets",
      "High waist",
    ],
  },
];
